/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ViewModel.HoaDonCTDoiTra;
import ViewModel.HoaDonDoiTraVM;
import ViewModel.HoaDonViewModel;
import ViewModel.TBGioHang;
import java.util.ArrayList;
import java.sql.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.HoaDonDoiTra;
import repository.BanHangRepo;
import repository.HoaDonDTRepo;
import service.HoaDonDoiTraSerVice;
import service.HoaDonService;
import service.impl.IHoaDonDoiTra;
import service.impl.IHoaDonS;

/**
 *
 * @author Admin
 */
public class QLDoiTra extends javax.swing.JFrame {

    /**
     * Creates new form QLDoiTra
     */
    BanHangRepo qlbh = new BanHangRepo();
    IHoaDonS qlhd = new HoaDonService();
    HoaDonDTRepo hddt = new HoaDonDTRepo();
    IHoaDonDoiTra qldt;
    DefaultComboBoxModel dfcb = new DefaultComboBoxModel();
    
    public QLDoiTra() {
        initComponents();
        qldt = new HoaDonDoiTraSerVice();
        loadTableHD();
        loadTableHDDT();
    }
    
    void loadTableHDCT() {
        int row = tbHD.getSelectedRow();
        if (row == -1) {
            return;
        }
        DefaultTableModel dftb = new DefaultTableModel();
        dftb = (DefaultTableModel) tbHDCT.getModel();
        
        ArrayList<HoaDonCTDoiTra> list = hddt.getListHDCT(tbHD.getValueAt(row, 0).toString());
        if (list != null) {
            
            dftb.setRowCount(0);
            for (HoaDonCTDoiTra gh : list) {
                dftb.addRow(new Object[]{
                    gh.getMaSP(), gh.getTenSP(), gh.getSoLuong(), String.format("%.0f", gh.getDonGia()), String.format("%.0f", gh.getTongTien()), gh.getSerial()
                });
            }
        } else {
            dftb.setRowCount(0);
        }
    }
    
    void addCBSN() {
        String ten = lbTenSP.getText();
        dfcb = (DefaultComboBoxModel) cbSN.getModel();
        dfcb.removeAllElements();
        for (String sn : qlbh.getListSerialNB(ten)) {
            dfcb.addElement(sn);
        }
    }
    
    void loadTableHD() {
        DefaultTableModel dftb = new DefaultTableModel();
        dftb = (DefaultTableModel) tbHD.getModel();
        dftb.setRowCount(0);
        for (HoaDonDoiTraVM hd : qlbh.getListHoaDonDoiTra()) {
            dftb.addRow(new Object[]{
                hd.getMaHD(), hd.getTenKhachHang(), hd.getNgayMua(), String.format("%.0f", hd.getTongTien()), hd.getNguoiTao()
            });
        }
    }
    
    void loadTableHDDT() {
        DefaultTableModel tbm = new DefaultTableModel();
        tbm = (DefaultTableModel) tbDoiTra.getModel();
        tbm.setRowCount(0);
        for (HoaDonDoiTraVM dt : qldt.getAllHDDTVM()) {
            tbm.addRow(new Object[]{
                dt.getMaHD(), dt.getMaHDDT(), dt.getMakh(), dt.getTenKhachHang(), dt.getSoluong(),String.format("%.0f", dt.getGia()) ,
                dt.getNgayDoiTra(), dt.getLidoDt(), dt.getNguoiTao()
            });
            
        }
    }

    private void clearForm() {
        lbTenKH.setText("");
        lbTenSP.setText("");
        cbSN.setSelectedIndex(0);
        cbLiDo.setSelectedIndex(0);
        txtSoLuong.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbSN = new javax.swing.JComboBox<>();
        lbTenKH = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoiTra = new javax.swing.JTable();
        lbTenSP = new javax.swing.JLabel();
        cbLiDo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHDCT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Đổi Trả"));

        jLabel1.setText("Họ Tên Khách Hàng:");

        jLabel2.setText("Tên Sản Phẩm");

        jLabel3.setText("Số Serial");

        cbSN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbTenKH.setText("_");

        jLabel5.setText("Lý Do ĐT:");

        tbDoiTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hoá Đơn", "Mã đổi trả", "Mã KH", "Tên Khách Hàng", "Số Lượng", "Giá", "Ngày Đổi Trả", "Lý Do Đổi Trả", "Người đổi trả"
            }
        ));
        jScrollPane1.setViewportView(tbDoiTra);

        lbTenSP.setText("_");

        cbLiDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lỗi bàn phím", "Lỗi màn hình", "Lỗi Pin ", "Máy nóng", "Lỗi ổ cứng", "Không cài được phần mềm" }));

        jButton1.setText("Đổi Trả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lượng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbLiDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbSN, 0, 173, Short.MAX_VALUE)))
                                    .addComponent(lbTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(45, 45, 45)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(lbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbTenKH))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbTenSP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbLiDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jButton1))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 358, 1006, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoá Đơn"));

        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hoá Đơn", "Tên Khách Hàng", "Ngày Mua", "Tổng Tiền", "Người Tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 318));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoá Đơn Chi Tiết"));

        tbHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Thành Tiền", "Số Serial"
            }
        ));
        tbHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDCTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbHDCT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseClicked
        // TODO add your handling code here:
        loadTableHDCT();
    }//GEN-LAST:event_tbHDMouseClicked

    private void tbHDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDCTMouseClicked
        // TODO add your handling code here:
        int rowhd = tbHD.getSelectedRow();
        int row = tbHDCT.getSelectedRow();
        if (row == -1 || rowhd == -1) {
            return;
        }
        lbTenKH.setText(tbHD.getValueAt(rowhd, 1).toString());
        lbTenSP.setText(tbHDCT.getValueAt(row, 1).toString());
        addCBSN();
    }//GEN-LAST:event_tbHDCTMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = tbHD.getSelectedRow();
        int rowhdct = tbHDCT.getSelectedRow();
        HoaDonDoiTraVM hd = qlbh.getListHoaDonDoiTra().get(row);
        HoaDonCTDoiTra hdct = hddt.getListHDCT(tbHD.getValueAt(row, 0).toString()).get(rowhdct);
//        System.out.println(hd.getIdNV());
//        System.out.println(hdct.getId());

        String nv = hd.getIdNV();
        String idhdct = hdct.getId();
        long millis = System.currentTimeMillis();
        Date ngaydt = new Date(millis);
        int soluong = Integer.parseInt(txtSoLuong.getText().trim());
        Random rd = new Random();
        String maHD = "HDDT" + rd.nextInt(1000);
        String lido = cbLiDo.getSelectedItem().toString();
        
        HoaDonDoiTra doitra = new HoaDonDoiTra();
        doitra.setMa(maHD);
        doitra.setSoLuong(soluong);
        doitra.setLido(lido);
        doitra.setIdhdct(idhdct);
        doitra.setIdnv(nv);
        doitra.setNgayDoi( ngaydt);
        qldt.insertHDDTRVMo(doitra);
        loadTableHDDT();
        clearForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDoiTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDoiTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDoiTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDoiTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDoiTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLiDo;
    private javax.swing.JComboBox<String> cbSN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTenSP;
    private javax.swing.JTable tbDoiTra;
    private javax.swing.JTable tbHD;
    private javax.swing.JTable tbHDCT;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
